version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-no-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1avr0ylgvc8ng"
s3_prefix = "sam-no-app"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"www-sam-no-app\""
